name = "OceanRasterConversions"
uuid = "07ff2621-03e0-4bfb-9812-e5d28c6dbff8"
authors = ["Josef I. Bisits <jbisits@gmail.com>"]
version = "0.2.0"

[deps]
GibbsSeaWater = "9a22fb26-0b63-4589-b28e-8f9d0b5c3d05"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"

[compat]
julia = "1.6"
Rasters = "^0.5.0"
GibbsSeaWater = "^0.1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
